name: Playwright Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Playwright tests inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tests \
            -w /tests \
            mcr.microsoft.com/playwright:v1.39.0-jammy \
            sh -c "npm install && npx playwright install && npx playwright test"
